# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'static/presets.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Presets(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(790, 290)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(560, 60, 151, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ClearSaveLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ClearSaveLayout.setContentsMargins(0, 0, 0, 0)
        self.ClearSaveLayout.setObjectName("ClearSaveLayout")
        self.ClearButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ClearButton.setObjectName("ClearButton")
        self.ClearSaveLayout.addWidget(self.ClearButton)
        self.SaveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.ClearSaveLayout.addWidget(self.SaveButton)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 20, 260, 223))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.presetbox_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.presetbox_label.setFont(font)
        self.presetbox_label.setAlignment(QtCore.Qt.AlignCenter)
        self.presetbox_label.setObjectName("presetbox_label")
        self.horizontalLayout_2.addWidget(self.presetbox_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.presets_list = QtWidgets.QListWidget(self.widget)
        self.presets_list.setObjectName("presets_list")
        item = QtWidgets.QListWidgetItem()
        self.presets_list.addItem(item)
        self.verticalLayout.addWidget(self.presets_list)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.accept_button = QtWidgets.QPushButton(self.widget)
        self.accept_button.setObjectName("accept_button")
        self.verticalLayout.addWidget(self.accept_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ClearButton.setText(_translate("Form", "Сбросить"))
        self.SaveButton.setText(_translate("Form", "Сохранить"))
        self.presetbox_label.setText(_translate("Form", "Пресеты"))
        __sortingEnabled = self.presets_list.isSortingEnabled()
        self.presets_list.setSortingEnabled(False)
        item = self.presets_list.item(0)
        item.setText(_translate("Form", "test"))
        self.presets_list.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("Form", "Удалить пресет"))
        self.pushButton.setText(_translate("Form", "Добавить пресет"))
        self.accept_button.setText(_translate("Form", "Принять"))
